Repository NeXi-Client/NeXi-Client, pull requests merged in 2020-09, with the labels that each got.

#31 Reworked Installer & fixed shortcut captial letters bug
  package.json
Labels: bug, enhancement, low priority

#32 Fixed Linkbox message
  main.js
Labels: bug, low priority, visual/ui

#33 Fix color code issue
  895025.json
  905193.json
  912228.json
  __game-scripts.js
  __game-scripts_old.js
  __nexi-client__.js
Labels: bug, low priority, visual/ui

#34 Added game-script changes to nexi-client.js
  __nexi-client__.js
Labels: enhancement, functionality, high priority

#35 Added all custom code into new JS file
  __nexi-client__.js
Labels: documentation, enhancement, functionality, high priority, visual/ui

#39 Fixed Linkbox Issue
  main.js
Labels: bug, functionality, high priority

#41 Overall Script Additions/Changes
  895025.json
  905193.json
  __game-scripts.js
  __nexi-client__.js
  files/assets/29307613/1/Scar_Diffuse.jpg
  files/assets/29307613/1/Scar_Diffuse_Backup.jpg
  files/assets/32463625/1/Shin-Default - Kopie - Kopie.jpg
  files/assets/32463625/1/Shin-Default.jpg
Labels: bug, enhancement, functionality, high priority, visual/ui

#62 Added more Comments into NeXi-Client script
  nexi-client.js
Labels: documentation

#66 Make NeXi-Client allowed in Tournaments
  895025.json
  905193.json
  files/assets/35571099/1/ghostUV1.jpg
  nexi-client.js
Labels: documentation, high priority, visual/ui
